### ISSUE TITLE
php app/console self:rightGroup:toggle username rightgroupname : erreur

### ISSUE THREAD

**Issue by xophe86** [InnovaLangues/self#1090]
Bonjour,
nous avons suivi votre readme.md. Nous avons installé et configuré Php 7.0, MariaDB, Nginx et Php-Fpm.

En essayant d'éxecuter php app/console self:rightGroup:toggle admin_self rightgroupname j'obtiens le message d'erreur suivant 

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Innova\SelfBundle\Manager\Right\RightGroupManager::toggleAll() must be an instance of Innova\SelfBundle\Entity\Right\RightGroup, null given, called in /var/www/html/self/src/Innova/SelfBundle/Command/RightGroupToggleCommand.php on line 32 in /var/www/html/self/src/Innova/SelfBundle/Manager/Right/RightGroupManager.php:38
Stack trace:
#0 /var/www/html/self/src/Innova/SelfBundle/Command/RightGroupToggleCommand.php(32): Innova\SelfBundle\Manager\Right\RightGroupManager->toggleAll(Object(Innova\SelfBundle\Entity\User), NULL)
#1 /var/www/html/self/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(256): Innova\SelfBundle\Command\RightGroupToggleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/self/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(849): Symfony\Component\Console\Command\Com in /var/www/html/self/src/Innova/SelfBundle/Manager/Right/RightGroupManager.php on line 38

Pouvez-vous m'aider ? Merci d'avance

**Comment by xophe86** [comment]
Je précise que j'ai pris la branche Master du GitHub.

**Comment by arnaudbey** [comment]
Bonjour

Il faut remplacer "righgroupname" par le nom d'un groupe de permissions ('rightgroup.tasks', 'rightgroup.tests', 'rightgroup.sessions', 'rightgroup.groups', 'rightgroup.users','rightgroup.exports')

bon courage !
